server:
  port: 8085
spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: -1
      retries: 1
    consumer:
      bootstrap-servers: localhost:9092
      group-id: groupA
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false
      ack-mode: manual
#  mail:
#    default-encoding: UTF-8
#    host: smtp.gmail.com
#    username: doanvanhiep230903@gmail.com
#